add typescript and vite
gabygarro/loficocotower pull request #26
Opened 2023-07-24 21:50 UTC by apucontilde

2023-07-24 22:25 UTC, jvsqzj commented
vite?

2023-07-28 02:49 UTC, gabygarro commented on src/utils.ts
> +  wait: number,
trailing space

2023-07-28 02:49 UTC, gabygarro requested changes
pls make the linter work

2023-07-28 02:50 UTC, gabygarro commented on src/index.tsx
> +import App from "./App.tsx"
```suggestion
import App from "./App"
```

2023-07-31 01:37 UTC, apucontilde commented on src/index.tsx
> +import App from "./App.tsx"
done!

2023-07-31 01:38 UTC, apucontilde commented on src/utils.ts
> +  wait: number,
done

2023-08-04 02:36 UTC, gabygarro approved these changes

2023-08-04 02:36 UTC, merged